### ISSUE TITLE
Undefined property: Log1x\AcfComposer\Console\BlockMakeCommand::$app

### ISSUE THREAD

**Issue by noonanwebgroup** [Log1x/acf-composer#73] opened 2021-03-01 13:19 UTC
After installing directly from Composer, I followed the docs and created a new block (`wp acorn acf:block Example`) and get the following error: In `MakeCommand.php line 156: Undefined property: Log1x\AcfComposer\Console\BlockMakeCommand::$app`.

As a result, the views don't get created. I'm not sure if there's something that I'm missing, as it looks like the code responsible has been there for some time and no issues have been raised prior.  I will create a PR with what got it working for me.

**Comment by Log1x** [comment] 2021-03-01 14:05
This appears to be due to a regression in Acorn

**Comment by Log1x** [comment] 2021-03-03 06:53
pushed a fix to acorn

**Closed by Log1x** 2021-03-03 06:53 UTC
